# Generated by Django 4.2.1 on 2023-06-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="user_name", new_name="name",
        ),
    ]
